apm install atom-beautify
apm install atom-jinja2
apm install auto-detect-indentation
apm install auto-indent
apm install auto-indent-file
apm install autoclose-html
apm install expose
apm install highlight-selected
apm install indent-guide-improved
apm install language-groovy
apm install language-salt
apm install linter
apm install linter-js-yaml
apm install linter-pep8
apm install linter-pydocstyle
apm install linter-pylint
apm install linter-ruby
apm install minimap
apm install minimap-highlight-selected
apm install monokai-seti
apm install multi-cursor
apm install multi-cursor-plus
apm install open-recent
apm install pigments
apm install seti-ui
apm install tabs-to-spaces
apm install todo-show
