vagrant plugin install sahara
vagrant plugin install vagrant-bindfs
vagrant plugin install vagrant-clean
vagrant plugin install vagrant-multiprovider-snap
vagrant plugin install vagrant-nfs_guest
vagrant plugin install vagrant-pristine
vagrant plugin install vagrant-saltdeps
vagrant plugin install vagrant-share
vagrant plugin install vagrant-timezone
vagrant plugin install vagrant-vbguest
vagrant plugin install vagrant-host-shell
vagrant plugin install vagrant-ip-show
vagrant plugin install vagrant-triggers
